default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: strava_analyzer_development

test:
  <<: *default
  database: strava_analyzer_test

production:
  primary: &primary_production
    <<: *default
    database: strava_analyzer_production
    username: strava_analyzer
    password: <%= ENV["STRAVA_ANALYZER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: strava_analyzer_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: strava_analyzer_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: strava_analyzer_production_cable
    migrations_paths: db/cable_migrate
